url: https://heydavid-dev.github.io
baseurl: /Agency-reload-22

# Site settings
header_title: Howdy Cowboy
header_subtitle: To infinity and beyond!

title: Awesome Title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: https://heydavid-dev.github.io
    - title: facebook
      url: https://heydavid-dev.github.io
    - title: stack-overflow
      url: https://heydavid-dev.github.io

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: https://heydavid-dev.github.io
    - title: facebook
      url: https://heydavid-dev.github.io
    - title: linkedin
      url: https://heydavid-dev.github.io

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: https://heydavid-dev.github.io
    - title: facebook
      url: https://heydavid-dev.github.io
    - title: google-plus
      url: https://heydavid-dev.github.io

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://heydavid-dev.github.io
  - title: facebook
    url: https://heydavid-dev.github.io
  - title: stack-overflow
    url: https://heydavid-dev.github.io
  - title: bitbucket 
    url: https://heydavid-dev.github.io
  - title: github
    url: https://heydavid-dev.github.io

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
